# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: azure tests pipeline AmusementPark

#this set your specic branch
trigger:
- azure-pipelines

# stages -> stage ->steps(1-n)
stages:
- stage: 'Build'
  displayName: 'build firs Job'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    pool:
     name: 'AZ-Pool'
    
    variables:
      nodeJsVersion: '20.x'

    steps:
    - checkout: self
      displayName: 'promise checkout code'
    - task: NodeTool@0
      displayName: 'set up node.js'
      inputs:
        versionSpec: '$(nodeJsVersion)'
    
    - script: npm install 
      displayName: 'Run install dependencies'
         
- stage: 'Test'
  displayName: 'Test stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
    - job: 'Test'
      displayName: 'Testing provided test scope'
      pool:
        name: 'AZ-Pool'

      steps:
      - checkout: self        
        displayName: 'Checkcout code for tests'
      
      - script: npm test
        displayName: 'Run tests'

      

# name: azure tests pipeline AmusementPark old
# trigger:
# - main

# pool:
#   name: 'AZ-Pool'

# steps:
# - task: NodeTool@0
#   displayName: 'Setup Node.js'
#   inputs:
#     versionSpec: '20.x'
    
# - script: npm install
#   displayName: 'Run tests'
  