name: azure tests pipeline AmusementPark

#this set your specic branch
trigger:
- azure-pipelines

# stages -> stage ->steps(1-n)
stages:
- stage: 'Build'
  displayName: 'build firs Job'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    pool:
     vmImage: 'ubuntu-latest'
    
    variables:
      nodeJsVersion: '20.x'

    steps:
    - checkout: self
      displayName: 'promise checkout code'
    - task: NodeTool@0
      displayName: 'set up node.js'
      inputs:
        versionSpec: '$(nodeJsVersion)'
    
    - script: npm install 
      displayName: 'Run install dependencies'
         
- stage: 'Test'
  displayName: 'Test stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
    - job: 'Test'
      displayName: 'Testing provided test scope'
      pool:
        name: 'AZ-Pool'

      steps:
      - checkout: self        
        displayName: 'Checkcout code for tests'
      
      - script: npm test
        displayName: 'Run tests'

      