# Starter pipeline

name: azure tests pipeline AmusementPark

#this set your specic branch
trigger:
- azure-pipelines

# stages -> stage ->steps(1-n)
stages:
- stage: 'Build'
  displayName: 'build firs Job'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    pool:
     name: 'AZ-Pool'
    
    variables:
      nodeJsVersion: '20.x'
    
    steps:
    - checkout: self
      displayName: 'promise checkout code'
    - task: NodeTool@0
      displayName: 'set up node.js'
      inputs:
        versionSpec: '$(nodeJsVersion)'
    
    - script: npm install 
      displayName: 'Run install dependencies'      
         
- stage: 'Test'
  displayName: 'Test stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
    - job: 'Test'
      steps:
      - checkout: self
      - script: |
          # Check if Angular CLI (ng) is installed
          if ! command -v ng &> /dev/null
          then
            echo "Angular CLI not found, installing..."
            npm install -g @angular/cli
          else
            echo "Angular CLI is already installed"
          fi

          # Run tests
          npm test
        displayName: 'Check and Install Angular CLI if Needed, Run tests'
        
      

# name: azure tests pipeline AmusementPark old
# trigger:
# - main

# pool:
#   name: 'AZ-Pool'

# steps:
# - task: NodeTool@0
#   displayName: 'Setup Node.js'
#   inputs:
#     versionSpec: '20.x'
    
# - script: npm install
#   displayName: 'Run tests'
  